# Changes here will be overwritten by Copier
_commit: v1.4.3
_src_path: gh:lincc-frameworks/python-project-template
author_email: sylvie.dagoret-campagne@ijclab.in2p3.fr
author_name: Sylvie Dagoret-Campagne
create_example_module: true
custom_install: true
include_benchmarks: true
include_docs: true
include_notebooks: true
mypy_type_checking: none
package_name: fitdiffatmo
preferred_linter: pylint
project_license: MIT
project_name: fitdiffatmo
use_gitlfs: none
use_isort: true
